"use client";

import { useEffect, useRef, useState } from "react";
import { Message } from "@/lib/firestore";
import MessageBubble from "./MessageBubble";
import TypingIndicator from "./TypingIndicator";
import ChatInput from "./ChatInput";
import NewsCard from "./NewsCard";
import { Zap, Globe, BookOpen, TrendingUp, FileText, Presentation, Volume2, Loader2 } from "lucide-react";
import { AIMode } from "./ChatInput";
import jsPDF from "jspdf";

import { SearchResult } from "@/lib/websearch";

interface ChatViewProps {
  chatId: string | null;
  messages: Message[];
  loading: boolean;
  error: string | null;
  newsArticles: SearchResult[] | null;
  mode: AIMode;
  onSend: (message: string, imageBase64?: string, imageMime?: string) => void;
  onModeChange: (mode: AIMode) => void;
}

const SUGGESTIONS = [
  { icon: TrendingUp, text: "What's happening in tech news today?", color: "text-violet-400" },
  { icon: Zap, text: "Explain quantum computing simply", color: "text-indigo-400" },
  { icon: Globe, text: "Latest AI developments in 2026", color: "text-blue-400" },
  { icon: BookOpen, text: "Summarize global economy trends", color: "text-purple-400" },
];

export default function ChatView({ chatId, messages, loading, error, newsArticles, mode, onSend, onModeChange }: ChatViewProps) {
  const bottomRef = useRef<HTMLDivElement>(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pptLoading, setPptLoading] = useState(false);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, loading]);

  const lastAiMessage = [...messages].reverse().find((m) => m.role === "assistant");

  const generatePDF = async () => {
    if (!lastAiMessage) return;
    setPdfLoading(true);
    try {
      const doc = new jsPDF();
      doc.setFontSize(16);
      doc.text("Firansi AI - Generated Document", 20, 20);
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(lastAiMessage.content.replace(/[#*`]/g, ""), 170);
      doc.text(lines, 20, 35);
      doc.save("firansi-ai-document.pdf");
    } finally {
      setPdfLoading(false);
    }
  };

  const generatePPT = async () => {
    if (!lastAiMessage) return;
    setPptLoading(true);
    try {
      const topic = messages.find((m) => m.role === "user")?.content ?? "Presentation";
      const res = await fetch("/api/ppt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);

      // Dynamic import pptxgenjs
      const PptxGenJS = (await import("pptxgenjs")).default;
      const pptx = new PptxGenJS();
      pptx.layout = "LAYOUT_WIDE";

      // Title slide
      const titleSlide = pptx.addSlide();
      titleSlide.background = { color: "0a0a0f" };
      titleSlide.addText(data.title, { x: 1, y: 2, w: 8, h: 1.5, fontSize: 36, bold: true, color: "a78bfa", align: "center" });
      titleSlide.addText("Generated by Firansi AI", { x: 1, y: 3.8, w: 8, h: 0.5, fontSize: 14, color: "6b7280", align: "center" });

      // Content slides
      for (const slide of data.slides) {
        const s = pptx.addSlide();
        s.background = { color: "0d0d14" };
        s.addText(slide.title, { x: 0.5, y: 0.3, w: 9, h: 0.8, fontSize: 24, bold: true, color: "a78bfa" });
        const bullets = slide.points.map((p: string) => ({ text: p, options: { bullet: true, fontSize: 16, color: "e5e7eb" } }));
        s.addText(bullets, { x: 0.5, y: 1.3, w: 9, h: 4 });
      }

      await pptx.writeFile({ fileName: "firansi-ai-presentation.pptx" });
    } catch (err: any) {
      alert("PPT generation failed: " + err.message);
    } finally {
      setPptLoading(false);
    }
  };

  const generateTTS = async () => {
    if (!lastAiMessage) return;
    // Use browser Web Speech API — completely free
    const utterance = new SpeechSynthesisUtterance(
      lastAiMessage.content.replace(/[#*`]/g, "").slice(0, 5000)
    );
    utterance.rate = 1;
    utterance.pitch = 1;
    utterance.lang = "en-US";
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  };

  const isEmpty = messages.length === 0;

  return (
    <div className="flex flex-col h-full bg-[#212121]">
      {/* Toolbar */}
      {lastAiMessage && !loading && (
        <div className="flex items-center gap-2 px-4 py-2 border-b border-white/[0.04] bg-[#0d0d14]">
          <span className="text-gray-600 text-xs mr-1">Export:</span>
          <button onClick={generatePDF} disabled={pdfLoading} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-red-400 bg-white/5 hover:bg-red-500/10 border border-white/8 px-2.5 py-1.5 rounded-lg transition-all">
            {pdfLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <FileText className="w-3 h-3" />} PDF
          </button>
          <button onClick={generatePPT} disabled={pptLoading} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-orange-400 bg-white/5 hover:bg-orange-500/10 border border-white/8 px-2.5 py-1.5 rounded-lg transition-all">
            {pptLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Presentation className="w-3 h-3" />} PPT
          </button>
          <button onClick={generateTTS} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-green-400 bg-white/5 hover:bg-green-500/10 border border-white/8 px-2.5 py-1.5 rounded-lg transition-all">
            <Volume2 className="w-3 h-3" /> Speak
          </button>
        </div>
      )}

      <div className="flex-1 overflow-y-auto scroll-smooth">
        {isEmpty && !loading ? (
          <WelcomeScreen onSuggestion={onSend} />
        ) : (
          <div className="max-w-3xl mx-auto px-4 pt-6 pb-4">
            {messages.map((msg) => <MessageBubble key={msg.id} message={msg} />)}
            {loading && <TypingIndicator />}
            {error && (
              <div className="mb-4 p-4 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 text-sm text-center">⚠ {error}</div>
            )}
            {newsArticles && newsArticles.length > 0 && !loading && <NewsCard articles={newsArticles} />}
            <div ref={bottomRef} />
          </div>
        )}
      </div>

      <ChatInput onSend={onSend} loading={loading} mode={mode} onModeChange={onModeChange} />    </div>
  );
}

function WelcomeScreen({ onSuggestion }: { onSuggestion: (s: string) => void }) {
  return (
    <div className="flex flex-col items-center justify-center h-full px-4 py-16 relative">
      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[300px] bg-violet-600/10 rounded-full blur-[100px] pointer-events-none" />
      <div className="relative z-10 flex flex-col items-center animate-scale-in">
        <div className="w-20 h-20 rounded-3xl overflow-hidden shadow-2xl shadow-violet-500/40 mb-6">
          <img src="/icon.png" alt="Firansi AI" className="w-full h-full object-contain bg-[#0d0d14]" />
        </div>
        <h2 className="text-4xl font-bold text-white mb-3 tracking-tight">Firansi AI</h2>
        <p className="text-gray-400 text-center max-w-sm mb-12 leading-relaxed">Ask me anything — questions, analysis, news, code, or just a conversation.</p>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 w-full max-w-2xl">
          {SUGGESTIONS.map(({ icon: Icon, text, color }) => (
            <button key={text} onClick={() => onSuggestion(text)} className="flex items-start gap-3 bg-white/[0.04] hover:bg-white/[0.08] border border-white/[0.08] hover:border-violet-500/30 rounded-2xl p-4 text-left transition-all duration-200 group">
              <div className="w-8 h-8 rounded-xl bg-white/5 flex items-center justify-center flex-shrink-0 group-hover:bg-violet-500/10 transition-colors">
                <Icon className={`w-4 h-4 ${color}`} />
              </div>
              <span className="text-gray-400 text-sm group-hover:text-gray-200 transition-colors leading-relaxed">{text}</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
